### PR TITLE
Almost complete.

### PR DESCRIPTION
**Pull request by LOLTATAIMAI**

### CODE REVIEW

**Comment by LOLTATAIMAI** [comment]
Fuck mainFrame!!!

i don't understand the way we do with mainFrame.
i think that mainFrame initially pictures TimeTablePanel.
what do you think mainFrame's behavior???

**Comment by lunasky-hy** [comment]
What did you do??
I don't want to resolve it...
OK. I try to resolve conflict. Please wait.

**Comment by lunasky-hy** [comment]
Complete merging into hiro branch.

**Comment by LOLTATAIMAI** [comment]
yamanaka fall down.

**Comment by LOLTATAIMAI** [comment]
interesting issues...

don't worry.

i can killlll them!!!

**Pull request closed without merging**
